-- Rodar no SQL Editor do projeto Supabase "Valores" (sydamnqagkdmczmgkvso)
create table public.controle_incidencias (
  id bigint generated by default as identity primary key,
  criado_em timestamptz not null default now(),
  preenchido_por text,
  tipo_ocorrencia text,
  tipo_prazo text,
  data_ocorrencia date,
  descricao text,
  data_identificacao date,
  data_comunicacao_socios date,
  relato_identificacao text,
  fator_contribuinte text,
  gravidade text,
  probabilidade_recorrencia text,
  profissional_envolvido text,
  profissional_envolvido_2 text,
  erro_compartilhado text,
  envolvimento_controladoria_deloitte text,
  equipe text,
  grupo text,
  avaliacao_profissional text,
  valor_caso numeric,
  valor_prejuizo numeric,
  licao_aprendida text,
  medidas_corretivas text,
  responsavel_acompanhamento text,
  sugestoes text,
  notificado_poliana boolean not null default false
);

alter table public.controle_incidencias enable row level security;

create policy "anon select" on public.controle_incidencias
  for select to anon using (true);

create policy "anon insert" on public.controle_incidencias
  for insert to anon with check (true);

create policy "anon update" on public.controle_incidencias
  for update to anon using (true);

alter publication supabase_realtime add table public.controle_incidencias;
